### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by i-guigon** [C3BI-pasteur-fr/ngphylogeny-django#13]
Hi there

I'm not sure this is the right place to post, but I used the "contact" form of [ngphylogeny.fr](https://ngphylogeny.fr/) and never got any answer.

I regularly get some "Error 500" when I use [ngphylogeny.fr](https://ngphylogeny.fr/) especially when I try to use the "à la carte" workflow. 
I cannot have a working workflow with MUSCLE or Clustal Omega, only MAFFT (and not all the time).
I randomly also have "Error 500" with the one click workflow 

Thank you for you help.

**Comment by fredericlemoine** [comment]
Hi,

Thank you for your message. I will have a look as soon as possible.

**Comment by i-guigon** [comment]
Hi,

Thank you for your answer.

I don't want to pressure you but the Galaxy instance is not working well either (I posted an issue on the dedicated GitHub project) so I can't work on my analyses :/

**Comment by fredericlemoine** [comment]
Thank you for the information

**Comment by fredericlemoine** [comment]
Dear @i-guigon , 

I think I found the issue with alacarte and Muscle. Can you give it a try?

Best,

Frederic

**Comment by i-guigon** [comment]
Dear Frederic,

I'm sorry, I just tried a "à la carte" workflow with MUSCLE but I still got an error 500...

Thank you for your help.

Isabelle

**Comment by fredericlemoine** [comment]
Thank you for your feedback,
Can you specify the tools you include in your workflow?
Frederic

**Comment by fredericlemoine** [comment]
I guess it was Muscle + FastTree? I updated the FastTree tool, can you try again? Thanks!

**Comment by i-guigon** [comment]
Yes I tried with MUSCLE and FastTree, and several alignments curation tools.
I just tried with MUSCLE + FastTree and MUSCLE + FastMe. It seems to be OK now.

Thank you very much!

**Comment by fredericlemoine** [comment]
Perfect, thanks!
